apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: shophub-discord
  namespace: shophub
spec:
  chart:
    spec:
      chart: ./shophub
      sourceRef:
        kind: GitRepository
        name: shophub-charts
      version: ">=0.1.0"
  interval: 1h
  values:
    discord:
      enabled: true
