apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kube-state-local
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/nikola031ue/kube-state
  ref:
    branch: feat/shop-replica