apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster.yaml
  - flux-source.yaml
  - helm-repo.yaml
  - namespace.yaml
  - shop-operator/helm.yaml
  - shophub/helm.yaml
  - shophub-discord/helm.yaml